
buildscript {
    ext.kotlin_version = '1.6.21'
    repositories {
        google()
        jcenter()
        mavenLocal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'com.google.ar.sceneform:plugin:1.17.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.21"

    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}